# Generated by Django 5.1.2 on 2026-01-30 11:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthdata',
            options={'ordering': ['-measured_at'], 'verbose_name': '健康データ', 'verbose_name_plural': '健康データ'},
        ),
        migrations.AlterModelOptions(
            name='sleepdata',
            options={'ordering': ['-date'], 'verbose_name': '睡眠データ', 'verbose_name_plural': '睡眠データ'},
        ),
        migrations.AddField(
            model_name='healthdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sleepdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sleepdata',
            name='sleep_quality',
            field=models.CharField(blank=True, choices=[('excellent', '非常に良い'), ('good', '良い'), ('poor', '悪い'), ('insufficient', '不足')], default='good', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='body',
            field=models.DecimalField(decimal_places=2, help_text='体温 (℃)', max_digits=4),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='heart_rate',
            field=models.IntegerField(help_text='心拍数 (bpm)'),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='measured_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='health_data', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sleepdata',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='sleepdata',
            name='sleep_hours',
            field=models.DecimalField(decimal_places=2, help_text='睡眠時間 (時間)', max_digits=4),
        ),
        migrations.AlterField(
            model_name='sleepdata',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='sleep_data', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='healthdata',
            index=models.Index(fields=['user', 'measured_at'], name='healthdata_user_id_bc5d21_idx'),
        ),
        migrations.AddIndex(
            model_name='healthdata',
            index=models.Index(fields=['measured_at'], name='healthdata_measure_27f2f6_idx'),
        ),
        migrations.AddIndex(
            model_name='sleepdata',
            index=models.Index(fields=['user', 'date'], name='sleepdata_user_id_16b7f7_idx'),
        ),
    ]
