# Generated by Django 5.1.2 on 2026-02-13 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, help_text='カスタムユーザーID (NU00001, NA00001など)', max_length=20)),
                ('action', models.CharField(choices=[('login', 'ログイン'), ('logout', 'ログアウト')], db_index=True, max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'access_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user_id', '-timestamp'], name='access_log_user_id_3072cd_idx')],
            },
        ),
    ]
