# Generated by Django 5.1.2 on 2026-01-08 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelpCategory',
            fields=[
                ('category_id', models.CharField(max_length=1, primary_key=True, serialize=False, verbose_name='カテゴリID（A〜Z）')),
                ('name', models.CharField(max_length=50, verbose_name='カテゴリ名')),
            ],
            options={
                'db_table': 'help_category',
            },
        ),
        migrations.CreateModel(
            name='HelpArticle',
            fields=[
                ('help_id', models.CharField(blank=True, max_length=4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, to='helpdesk.helpcategory')),
            ],
            options={
                'db_table': 'help',
            },
        ),
    ]
